# Generated by Django 4.2.10 on 2024-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
